/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataRouteImport } from './routes/data'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ScenariosRouteImport } from './routes/scenarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/income': typeof IncomeRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/income': typeof IncomeRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/income': typeof IncomeRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/accuracy' | '/dashboard' | '/data' | '/income' | '/scenarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accuracy' | '/dashboard' | '/data' | '/income' | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/dashboard'
    | '/data'
    | '/income'
    | '/scenarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  IncomeRoute: typeof IncomeRoute
  ScenariosRoute: typeof ScenariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  IncomeRoute: IncomeRoute,
  ScenariosRoute: ScenariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
